import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './tag/LoginBtn'
import LogoutBtn from './tag/LogoutBtn'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { getServerSession} from 'next-auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <div className="navbar"> 
          <Link href="/" className="logo">AnimalAnywhere</Link> 
          <Link href="/list">List</Link> 
          {
          session ? (<LogoutBtn></LogoutBtn>):(<LoginBtn></LoginBtn>)
          }
        </div>  
        {children}
      </body>
    </html>
    
  )
}
